### ISSUE TITLE
Site down?

### ISSUE THREAD

**Issue by adamrneary** [ovidiuch/aufond#98]
I just checked in and was going to make a few updates, but I am getting nothing at aufond.me. Is this a temporary thing, or is the hosted version shut down?

Thanks!

**Comment by ovidiuch** [comment]
Rackspace seems to have had quite a few issues lately, but everything seems
back up at the moment. Can you confirm?

Not planning to shut down the hosted version in any way, sorry for the
inconvenience!

On Wednesday, March 19, 2014, Adam Neary notifications@github.com wrote:

> I just checked in and was going to make a few updates, but I am getting
> nothing at aufond.me. Is this a temporary thing, or is the hosted version
> shut down?
> 
> Thanks!
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/skidding/aufond/issues/98
> .

## 

Best regards,
Ovidiu Cherecheş

**Comment by adamrneary** [comment]
Back up. Sorry for the false alarm!
